### PR TITLE
Add method to delete Zone by Id

### PR DESCRIPTION
**Pull request by cmperdomoc**

### CODE REVIEW

**Comment by Yannik** [comment]
@cmperdomoc don't you think that deleting zones by `zoneName` would be far more useful? zone names are also unique but also human friendly. i'd suggest changing the method to use that.

**Comment by cmperdomoc** [comment]
You're right @Yannik, changed it to identify the zone by Name

**Comment by Yannik** [comment]
@cmperdomoc thanks, can you please squash this into one commit and please note that nouns like `name` and `id` should be lowercase in english.

**Review by Yannik — APPROVED** [review]

**Comment by Yannik** [comment]
@cmperdomoc well done! :)

**Pull request merged**
